container:
  containerimage: "OVERWRITE.acr.io/alwayson/healthservice:1234" # Container Image Name
  pullPolicy: "IfNotPresent" # Container Image Pull Policy. Using IfNotPresent to enable pod starts even if ACR cannot be reached and image was pulled on the node previously

workload:
  port: 8080 # Port of the container workload
  service:
    port: 80 # Service Port (not used for Ingress)
    type: "ClusterIP" # Service Type (default ClusterIP)

replicas: 3

# Note! When disabling Network Policy for this helm chart,
# make sure to disable Network Policy for the CatalogService as well
# as it contains a default-deny policy.
networkPolicy:
  enabled: true # Enable Network Policy

azure:
  region: "East US 2"
