{{- if .Values.networkPolicy.enabled }}
# Network Policy to allow ingress traffic from * to the workload.
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ .Chart.Name }}-allow-ingress
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
spec:
  podSelector:
    matchLabels:
      app: {{ .Chart.Name }}
  ingress:
  - from: []
    ports:
    - port: {{ .Values.workload.port | default 8080 }}
---
# Network policy to allow egress / outbound traffic from the workload.
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Chart.Name }}-allow-egress-traffic
spec:
  podSelector:
    matchLabels:
      app: {{ .Chart.Name }}
  egress:
  - to:
    - ipBlock:
        cidr: {{ .Values.networkPolicy.egressRange | default "0.0.0.0/0" }} 
  policyTypes:
  - Egress
---
# Network policy to allow dns egress
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Chart.Name }}-allow-egress-dns
spec:
  podSelector:
    matchLabels:
      app: {{ .Chart.Name }}
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: kube-system
    ports:
    - protocol: UDP # UDP/53 allows DNS traffic
      port: 53
    - protocol: TCP # TCP/53 allows DNS traffic
      port: 53
  policyTypes:
  - Egress
{{- end }}